name: capstone_project
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fancy_bottom_navigation: ^0.3.3
  carousel_slider: ^4.1.1
  http: ^0.13.3
  file_picker: ^4.3.0
  intl: ^0.17.0
  flutter_html: ^2.2.1
  sizer: ^2.0.15
  flutter_share_me: ^1.3.0
  font_awesome_flutter: ^10.1.0
  shared_preferences: ^2.0.15
  image_picker: ^0.8.5+3
  path_provider: ^2.0.11
  fluttertoast: ^8.0.9
  flutter_sound: ^9.2.13
  permission_handler: ^10.0.0
  audioplayers: ^1.0.1
  flutter_screenutil: ^5.5.3+2
  firebase_core: ^1.19.2
  firebase_auth: ^3.4.2
  firebase_storage: ^10.3.2
  firebase_messaging: ^12.0.0
  firebase_app_check: ^0.0.6+17
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/images/

